
CREATE TABLE RECAUDABANCONACIONSOLES
(
  TIPO    NUMBER(1),
  CAMPO   VARCHAR2(500 BYTE)
);
COMMENT ON COLUMN RECAUDABANCONACIONSOLES.TIPO IS '0: Suma Importes / 1: Conteo Creditos / 2: Trama';

CREATE TABLE RECAUDABANCONACIONDOLARES
(
  TIPO    NUMBER(1),
  CAMPO   VARCHAR2(500 BYTE)
);
COMMENT ON COLUMN RECAUDABANCONACIONDOLARES.TIPO IS '0: Suma Importes / 1: Conteo Creditos / 2: Trama';