
CREATE TABLE SISGODBA.RECAUDABANCONACIONSOLES
(
  TIPO    NUMBER(1),
  CAMPO   VARCHAR2(500 BYTE)
);

CREATE TABLE SISGODBA.RECAUDABANCONACIONDOLARES
(
  TIPO    NUMBER(1),
  CAMPO   VARCHAR2(500 BYTE)
);